name: Java CI with GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Package Java App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: insured-app-war
          path: target/insured-assurance.war

  trigger-jenkins:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Webhook Remote Jenkins Pipeline
        run: |
          curl -X POST "https://sip-proclaim-magnify.ngrok-free.dev/job/Insured-Assurance-CD/build?token=INSURED_SECRET_TOKEN" || true